id: I88C50EA2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T15:08:34+00:00'
last_modified: '2022-06-08T06:40:06.386381+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD104698
  title: གྲོ་ལུང་པ་བློ་གྲོས་འབྱུང་གནས་ཀྱི་གསུང་ཆོས་སྐོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C3D3:
      image_group_id: I1KG5853
      title: ''
      total_pages: 834
      order: 1
      base_file: C3D3.txt
    '2246':
      image_group_id: I1KG5854
      title: ''
      total_pages: 945
      order: 2
      base_file: 2246.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
